### ISSUE TITLE
No arch support?

### ISSUE THREAD

**Issue by DaniAffCH** [tansrv/tanserver#1]
Can the framework be used on arch and its derivate?

**Comment by chen-da-ye** [comment]
Please wait, I am testing now and then update the documentation. It may take several hours.

**Comment by chen-da-ye** [comment]
The documentation has been updated: https://www.tanserver.org/#/install

Install via the following script:

```shell
wget https://github.com/tansrv/tanserver/releases/download/latest-version/tanserver.tar.gz
sudo tar -zxvf tanserver.tar.gz
cd tanserver/install && sudo ./pacman-install.sh
```
